import json
import os

import joblib
import pandas as pd

SEGMENTER_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "customer_segmenter.pkl")
SEGMENT_METADATA_PATH = os.path.join(os.path.dirname(__file__), "..", "models", "segment_metadata.json")

EXPECTED_SEGMENT_FEATURES = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges",
    "Contract",
    "InternetService",
    "PaymentMethod",
]


def _load_segmenter_assets():
    if not os.path.exists(SEGMENTER_PATH):
        raise FileNotFoundError(
            "Segmentation model not found. Train models by running backend/ml/train_model.py"
        )

    segmenter = joblib.load(SEGMENTER_PATH)

    metadata = {}
    if os.path.exists(SEGMENT_METADATA_PATH):
        with open(SEGMENT_METADATA_PATH, "r", encoding="utf-8") as file_obj:
            metadata = json.load(file_obj)

    return segmenter, metadata


def segment_from_payload(payload):
    missing = [feature for feature in EXPECTED_SEGMENT_FEATURES if feature not in payload]
    if missing:
        raise ValueError(f"Missing required segmentation features: {', '.join(missing)}")

    segmenter, metadata = _load_segmenter_assets()

    row = {feature: payload[feature] for feature in EXPECTED_SEGMENT_FEATURES}
    input_df = pd.DataFrame([row])

    cluster_id = int(segmenter.predict(input_df)[0])
    profile = metadata.get(str(cluster_id), {})

    return {
        "segment_id": cluster_id,
        "segment_name": profile.get("segment_name", f"Cluster {cluster_id}"),
        "segment_description": profile.get(
            "segment_description", "Cluster generated by KMeans segmentation"
        ),
        "segment_profile": profile,
    }


def get_segment_summary():
    _, metadata = _load_segmenter_assets()

    segments = []
    total_customers = 0
    for cluster_id, profile in metadata.items():
        size = int(profile.get("size", 0))
        total_customers += size
        segments.append(
            {
                "segment_id": int(cluster_id),
                "segment_name": profile.get("segment_name", f"Cluster {cluster_id}"),
                "segment_description": profile.get("segment_description", ""),
                "avg_tenure": profile.get("avg_tenure"),
                "avg_monthly_charges": profile.get("avg_monthly_charges"),
                "dominant_contract": profile.get("dominant_contract"),
                "size": size,
            }
        )

    segments.sort(key=lambda item: item["segment_id"])

    return {
        "model": "KMeans",
        "segment_count": len(segments),
        "total_customers": total_customers,
        "segments": segments,
    }
